# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8271831e6536fa0fbd522601921d344db4bdddcd1d31f1e14e62dce9dfcbe49dfa54d3f6ff8f93ed0641f0b9cf640c07df27673b19debc3de83e18ff0ccb1afe

test:
  secret_key_base: 27f493211b08f7983c0cf04a96472bdcd3c500be30985eb47ce71335b5681ce0dfca7de130c4efd4c1adf256fc962e76d4f5058d670450d631530b0f2c86c088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
